package com.crowdshield.activity;

public enum ActivityAction {
    LOGIN,
    ALERT_CREATED,
    INCIDENT_RESOLVED,
    EMERGENCY_DISPATCHED,
    USER_CREATED,
    SETTINGS_CHANGED,
    REGISTER,
    INCIDENT_CREATED,
    ROLE_CHANGED,
    CAMERA_CREATED,
    CAMERA_UPDATED,
    SYSTEM_EVENT
}
