import {
  AlertItem,
  AuditLogItem,
  CameraStream,
  EmergencyProtocol,
  IncidentRecord,
  StatMetric,
  SystemConfigSettings,
  UserAccount,
  ZoneAnalytics,
} from "@/types/domain";

export const MOCK_OVERVIEW_METRICS: StatMetric[] = [
  {
    title: "Total Live Occupancy",
    value: "42,850",
    change: "+12.4%",
    isPositive: true,
    icon: "groups",
    description: "Across 8 monitored sectors",
  },
  {
    title: "Active Threat Alerts",
    value: "14",
    change: "-2 from last hour",
    isPositive: true,
    icon: "warning",
    description: "3 High Severity",
  },
  {
    title: "Cameras Online",
    value: "248 / 252",
    change: "98.4%",
    isPositive: true,
    icon: "videocam",
    description: "4 cameras scheduled for maintenance",
  },
  {
    title: "Avg Dwell Time",
    value: "28.5 min",
    change: "+4.2 min",
    isPositive: false,
    icon: "timer",
    description: "Main Plaza & North Gate",
  },
];

export const MOCK_ZONE_ANALYTICS: ZoneAnalytics[] = [
  {
    zoneId: "ZONE-01",
    zoneName: "Main Entrance Plaza",
    capacityPercentage: 88,
    currentDensity: 14200,
    maxCapacity: 16000,
    dwellTimeMinutes: 18.5,
    flowRateIn: 450,
    flowRateOut: 380,
    status: "congested",
  },
  {
    zoneId: "ZONE-02",
    zoneName: "North Concourse & Food Court",
    capacityPercentage: 94,
    currentDensity: 11280,
    maxCapacity: 12000,
    dwellTimeMinutes: 42.0,
    flowRateIn: 210,
    flowRateOut: 190,
    status: "critical",
  },
  {
    zoneId: "ZONE-03",
    zoneName: "East Promenade",
    capacityPercentage: 45,
    currentDensity: 6750,
    maxCapacity: 15000,
    dwellTimeMinutes: 12.2,
    flowRateIn: 320,
    flowRateOut: 340,
    status: "normal",
  },
  {
    zoneId: "ZONE-04",
    zoneName: "South Transit Terminal",
    capacityPercentage: 72,
    currentDensity: 10800,
    maxCapacity: 15000,
    dwellTimeMinutes: 24.8,
    flowRateIn: 610,
    flowRateOut: 580,
    status: "moderate",
  },
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "ALT-9042",
    title: "High Crowd Surge Detected",
    description: "Density surpassed 92% safe threshold near Turnstile 4.",
    location: "North Concourse - Turnstile 4",
    timestamp: "10 mins ago",
    severity: "critical",
    status: "active",
    cameraId: "CAM-014",
    assignedOfficer: "Capt. Marcus Vance",
  },
  {
    id: "ALT-9041",
    title: "Unattended Baggage Alert",
    description: "Object stationary for >15 minutes identified by AI Vision.",
    location: "East Promenade - Bench 12",
    timestamp: "24 mins ago",
    severity: "high",
    status: "active",
    cameraId: "CAM-088",
    assignedOfficer: "Officer Sarah Chen",
  },
  {
    id: "ALT-9040",
    title: "Perimeter Barrier Tamper",
    description: "Optical sensor movement detected on Gate 7 outer fence.",
    location: "South Perimeter Gate 7",
    timestamp: "45 mins ago",
    severity: "medium",
    status: "acknowledged",
    cameraId: "CAM-120",
    assignedOfficer: "Sgt. David Miller",
  },
  {
    id: "ALT-9039",
    title: "Camera Feeds Interrupted",
    description: "Transient network latency on Fiber Loop B.",
    location: "West Parking Garage Level 3",
    timestamp: "1 hour ago",
    severity: "low",
    status: "resolved",
    cameraId: "CAM-204",
  },
];

export const MOCK_CAMERAS: CameraStream[] = [
  {
    id: "CAM-014",
    name: "North Turnstile PTZ",
    zone: "North Concourse",
    ipAddress: "192.168.10.14",
    status: "online",
    resolution: "4K UHD (3840x2160)",
    fps: 60,
    streamUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=800&q=80",
    detectionActive: true,
    type: "Optical PTZ",
  },
  {
    id: "CAM-088",
    name: "East Promenade Thermal AI",
    zone: "East Promenade",
    ipAddress: "192.168.10.88",
    status: "online",
    resolution: "1080p FHD",
    fps: 30,
    streamUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80",
    detectionActive: true,
    type: "Thermal AI",
  },
  {
    id: "CAM-120",
    name: "South Gate 7 Fence Outer",
    zone: "South Perimeter",
    ipAddress: "192.168.10.120",
    status: "warning",
    resolution: "1080p FHD",
    fps: 24,
    streamUrl: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
    detectionActive: true,
    type: "Fixed Wide-Angle",
  },
  {
    id: "CAM-204",
    name: "West Garage Level 3 Main",
    zone: "West Garage",
    ipAddress: "192.168.10.204",
    status: "maintenance",
    resolution: "720p HD",
    fps: 15,
    streamUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
    detectionActive: false,
    type: "Fixed Wide-Angle",
  },
];

export const MOCK_INCIDENTS: IncidentRecord[] = [
  {
    id: "INC-2026-0891",
    title: "Turnstile 4 Crowd Bottleneck Surge",
    category: "Crowd Control",
    zone: "North Concourse",
    reportedAt: "10:14:22 AM",
    severity: "critical",
    status: "dispatched",
    assignedTo: "Capt. Marcus Vance",
    responseUnits: ["Tactical Squad Alpha", "Medical Unit 2"],
    notes: [
      "Deploying secondary barriers to reroute foot traffic.",
      "Turnstiles 5 & 6 opened manually.",
    ],
  },
  {
    id: "INC-2026-0890",
    title: "Unattended Luggage Inspection",
    category: "Perimeter Security",
    zone: "East Promenade",
    reportedAt: "09:48:10 AM",
    severity: "high",
    status: "investigating",
    assignedTo: "Officer Sarah Chen",
    responseUnits: ["K9 Unit 4"],
    notes: ["Scanner anomaly flagged by AI vision pipeline."],
  },
];

export const MOCK_EMERGENCY_PROTOCOLS: EmergencyProtocol[] = [
  {
    id: "EP-RED-01",
    name: "FULL FACILITY EVACUATION",
    code: "CODE RED ALPHA",
    activeState: false,
    description: "Immediately triggers all emergency exits, broadcasts loud public address alert, and notifies central emergency dispatchers.",
    requiredClearance: "SUPER_ADMIN",
    steps: [
      "Automated siren activation & PA vocal announcement.",
      "All turnstiles & fire exits automatically unlatched.",
      "Elevator systems locked to Ground Return Mode.",
      "Local Fire Department & Municipal Police telemetry stream initialized."
    ],
    affectedZones: ["All Zones (1 through 8)"],
  },
  {
    id: "EP-ORANGE-02",
    name: "PERIMETER SECTOR LOCKOUT",
    code: "CODE ORANGE BRAVO",
    activeState: false,
    description: "Isolates outer perimeter security gates while retaining normal egress inside main stadium halls.",
    requiredClearance: "SECURITY_OPERATOR",
    steps: [
      "Outer turnstile entry gates lock to incoming traffic.",
      "Outer fence cameras switched to continuous 60fps tracking mode.",
      "Rapid Response Tactical Squad dispatched to perimeter outer bounds."
    ],
    affectedZones: ["Zone 01", "Zone 04"],
  },
];

export const MOCK_USERS: UserAccount[] = [
  {
    id: "USR-001",
    name: "Alex Mercer",
    email: "a.mercer@crowdshield.internal",
    role: "Super Admin",
    department: "Executive Command",
    status: "active",
    lastActive: "Just now",
  },
  {
    id: "USR-002",
    name: "Capt. Marcus Vance",
    email: "m.vance@crowdshield.internal",
    role: "Security Officer",
    department: "Field Tactical Ops",
    status: "active",
    lastActive: "5 mins ago",
  },
  {
    id: "USR-003",
    name: "Sarah Chen",
    email: "s.chen@crowdshield.internal",
    role: "Field Dispatcher",
    department: "Response Coordination",
    status: "active",
    lastActive: "12 mins ago",
  },
  {
    id: "USR-004",
    name: "David Miller",
    email: "d.miller@crowdshield.internal",
    role: "Data Auditor",
    department: "Compliance & Risk",
    status: "inactive",
    lastActive: "2 days ago",
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: "LOG-8801",
    timestamp: "2026-08-06 13:42:10",
    user: "Alex Mercer (Super Admin)",
    action: "Updated AI Detection Sensitivity to High (0.85)",
    category: "System Config",
    ipAddress: "10.200.4.15",
    status: "SUCCESS",
  },
  {
    id: "LOG-8800",
    timestamp: "2026-08-06 13:28:45",
    user: "Capt. Marcus Vance",
    action: "Acknowledged Critical Alert ALT-9042",
    category: "Security",
    ipAddress: "10.200.4.88",
    status: "SUCCESS",
  },
  {
    id: "LOG-8799",
    timestamp: "2026-08-06 12:15:02",
    user: "System Daemon",
    action: "Automated Routine Camera Health Diagnostics",
    category: "Security",
    ipAddress: "127.0.0.1",
    status: "SUCCESS",
  },
  {
    id: "LOG-8798",
    timestamp: "2026-08-06 11:04:19",
    user: "Sarah Chen",
    action: "Failed login attempt (Invalid credentials)",
    category: "User Management",
    ipAddress: "192.168.1.104",
    status: "FAILED",
  },
];

export const MOCK_SYSTEM_CONFIG: SystemConfigSettings = {
  aiSensitivity: 85,
  autoDispatchThreshold: 90,
  retentionDays: 30,
  emailNotifications: true,
  smsAlerts: true,
  webhookUrl: "https://api.crowdshield.internal/v1/telemetry/webhooks",
  darkThemeEnabled: false,
  emergencyProtocolAutoTrigger: false,
};
